@startuml usecase_quan_sat_ve_tinh
skinparam defaultFontName "Times New Roman"
skinparam linetype polyline
left to right direction
title Use case phân rã: Quan sát vệ tinh

actor "Người dùng" as User
actor "Dịch vụ dữ liệu ngoài" as Ext

rectangle "Quan sát vệ tinh" {
  usecase "Xem danh sách vệ tinh" as U1
  usecase "Xem vệ tinh trên mô hình 3D" as U2
  usecase "Xem vệ tinh bằng AR" as U3
  usecase "Cập nhật dữ liệu quỹ đạo" as U4
  usecase "Xem chi tiết vệ tinh" as U5
}

User --> U1
User --> U2
User --> U3
User --> U4
User --> U5
Ext --> U4
@enduml
