@startuml usecase_tong_quat
skinparam defaultFontName "Times New Roman"
title Use case tong quat
left to right direction
skinparam packageStyle rectangle

actor "Nguoi dung" as User
actor "Backend xu ly video\n(My/Outer Server)" as Backend
actor "Dich vu du lieu ngoai\n(Nominatim/OSRM, IGS, CelesTrak)" as External

rectangle "GNSSAndOpticalFlowApp" {
  usecase "Xem ban do GNSS hai chieu" as UC1
  usecase "Xem ve tinh tren mo hinh 3D/AR" as UC2
  usecase "Chi duong truc tiep co ho tro Optical Flow" as UC3
  usecase "Phan tich camera bang Optical Flow" as UC4
  usecase "Phan tich hieu nang KLT/Farneback" as UC5
  usecase "Xu ly video bang RAFT" as UC6
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6

External --> UC1
External --> UC2
External --> UC3
Backend --> UC6

UC3 ..> UC4 : include
UC5 ..> UC4 : include
@enduml
