@startuml usecase_tong_quat
skinparam defaultFontName "Times New Roman"
left to right direction
skinparam packageStyle rectangle
skinparam nodesep 12
title Use case tổng quát

actor "Người dùng" as User

rectangle "GNSSAndOpticalFlowApp" {
  usecase "Quan sát vệ tinh" as UC1
  usecase "Xem bản đồ hai chiều" as UC2
  usecase "Chỉ đường trực tiếp" as UC3
  usecase "Xem Optical Flow trên Camera" as UC4
  usecase "Phân tích hiệu năng Optical Flow" as UC5
  usecase "Xử lý video Optical Flow\nbằng mô hình mạng lưới học sâu" as UC6
  usecase "Xem lưu trữ" as UC7
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
User --> UC7
@enduml
