@startuml usecase_xem_ban_do
skinparam defaultFontName "Times New Roman"
left to right direction
skinparam packageStyle rectangle
skinparam linetype ortho
skinparam nodesep 35
skinparam ranksep 50
title Use case phân rã: Xem bản đồ hai chiều

actor "Người dùng" as User

rectangle "Xem bản đồ hai chiều" {
  usecase "Xem vị trí hiện tại" as U1
  usecase "Tìm kiếm địa điểm" as U2
  usecase "Xem tuyến đường\ntừ điểm A đến điểm B" as U3

  U1 -[hidden]down- U2
  U2 -[hidden]down- U3
}

User --> U1
User --> U2
User --> U3

U3 ..> U2 : <<extend>>
@enduml
